version: '3'

services:
  db:
    image: postgres
    container_name: ddd-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: beyondnet
      POSTGRES_PASSWORD: beyondnet

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: beyondnet.peru@gmail.com
      PGADMIN_DEFAULT_PASSWORD: beyondnet
    ports:
      - '5050:80'
